version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: Inyector.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - davidrevoledo@d-genix.com
  subject: '[AppVeyor] - Inyector'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true